#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_atendimentos")]
	public partial class atendimentosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertunidade_medida(unidade_medida instance);
    partial void Updateunidade_medida(unidade_medida instance);
    partial void Deleteunidade_medida(unidade_medida instance);
    partial void Insertcurso(curso instance);
    partial void Updatecurso(curso instance);
    partial void Deletecurso(curso instance);
    partial void Insertempresa(empresa instance);
    partial void Updateempresa(empresa instance);
    partial void Deleteempresa(empresa instance);
    partial void Insertgrupo_curso(grupo_curso instance);
    partial void Updategrupo_curso(grupo_curso instance);
    partial void Deletegrupo_curso(grupo_curso instance);
    partial void Insertgrupo_procedimento(grupo_procedimento instance);
    partial void Updategrupo_procedimento(grupo_procedimento instance);
    partial void Deletegrupo_procedimento(grupo_procedimento instance);
    partial void Insertgrupo_produto(grupo_produto instance);
    partial void Updategrupo_produto(grupo_produto instance);
    partial void Deletegrupo_produto(grupo_produto instance);
    partial void Insertprocedimento(procedimento instance);
    partial void Updateprocedimento(procedimento instance);
    partial void Deleteprocedimento(procedimento instance);
    partial void Insertproduto(produto instance);
    partial void Updateproduto(produto instance);
    partial void Deleteproduto(produto instance);
    partial void Insertfornecedor(fornecedor instance);
    partial void Updatefornecedor(fornecedor instance);
    partial void Deletefornecedor(fornecedor instance);
    #endregion
		
		public atendimentosDataContext() : 
				base(global::DAO.Properties.Settings.Default.db_atendimentosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public atendimentosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public atendimentosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public atendimentosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public atendimentosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> cliente
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<unidade_medida> unidade_medida
		{
			get
			{
				return this.GetTable<unidade_medida>();
			}
		}
		
		public System.Data.Linq.Table<curso> curso
		{
			get
			{
				return this.GetTable<curso>();
			}
		}
		
		public System.Data.Linq.Table<empresa> empresa
		{
			get
			{
				return this.GetTable<empresa>();
			}
		}
		
		public System.Data.Linq.Table<grupo_curso> grupo_curso
		{
			get
			{
				return this.GetTable<grupo_curso>();
			}
		}
		
		public System.Data.Linq.Table<grupo_procedimento> grupo_procedimento
		{
			get
			{
				return this.GetTable<grupo_procedimento>();
			}
		}
		
		public System.Data.Linq.Table<grupo_produto> grupo_produto
		{
			get
			{
				return this.GetTable<grupo_produto>();
			}
		}
		
		public System.Data.Linq.Table<procedimento> procedimento
		{
			get
			{
				return this.GetTable<procedimento>();
			}
		}
		
		public System.Data.Linq.Table<produto> produto
		{
			get
			{
				return this.GetTable<produto>();
			}
		}
		
		public System.Data.Linq.Table<fornecedor> fornecedor
		{
			get
			{
				return this.GetTable<fornecedor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_cliente")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private string _tipo;
		
		private string _cpf_cnpj;
		
		private string _rg_ie;
		
		private System.Nullable<System.DateTime> _data_nascimento;
		
		private string _estado_civil;
		
		private System.Nullable<char> _sexo;
		
		private string _cep;
		
		private string _logradouro;
		
		private string _numero;
		
		private string _complemento;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _estado;
		
		private string _ddd;
		
		private string _telefone;
		
		private string _celular;
		
		private string _email;
		
		private System.DateTime _data_cadastro;
		
		private byte _ativo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void Oncpf_cnpjChanging(string value);
    partial void Oncpf_cnpjChanged();
    partial void Onrg_ieChanging(string value);
    partial void Onrg_ieChanged();
    partial void Ondata_nascimentoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_nascimentoChanged();
    partial void Onestado_civilChanging(string value);
    partial void Onestado_civilChanged();
    partial void OnsexoChanging(System.Nullable<char> value);
    partial void OnsexoChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnlogradouroChanging(string value);
    partial void OnlogradouroChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OndddChanging(string value);
    partial void OndddChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondata_cadastroChanging(System.DateTime value);
    partial void Ondata_cadastroChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_cliente", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_cliente", Storage="_nome", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tipo_cliente", Storage="_tipo", DbType="VarChar(2)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf_cnpj", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string cpf_cnpj
		{
			get
			{
				return this._cpf_cnpj;
			}
			set
			{
				if ((this._cpf_cnpj != value))
				{
					this.Oncpf_cnpjChanging(value);
					this.SendPropertyChanging();
					this._cpf_cnpj = value;
					this.SendPropertyChanged("cpf_cnpj");
					this.Oncpf_cnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg_ie", DbType="VarChar(15)")]
		public string rg_ie
		{
			get
			{
				return this._rg_ie;
			}
			set
			{
				if ((this._rg_ie != value))
				{
					this.Onrg_ieChanging(value);
					this.SendPropertyChanging();
					this._rg_ie = value;
					this.SendPropertyChanged("rg_ie");
					this.Onrg_ieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nascimento", DbType="Date")]
		public System.Nullable<System.DateTime> data_nascimento
		{
			get
			{
				return this._data_nascimento;
			}
			set
			{
				if ((this._data_nascimento != value))
				{
					this.Ondata_nascimentoChanging(value);
					this.SendPropertyChanging();
					this._data_nascimento = value;
					this.SendPropertyChanged("data_nascimento");
					this.Ondata_nascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_civil", DbType="VarChar(15)")]
		public string estado_civil
		{
			get
			{
				return this._estado_civil;
			}
			set
			{
				if ((this._estado_civil != value))
				{
					this.Onestado_civilChanging(value);
					this.SendPropertyChanging();
					this._estado_civil = value;
					this.SendPropertyChanged("estado_civil");
					this.Onestado_civilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="Char(1)")]
		public System.Nullable<char> sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(15)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logradouro", DbType="VarChar(80)")]
		public string logradouro
		{
			get
			{
				return this._logradouro;
			}
			set
			{
				if ((this._logradouro != value))
				{
					this.OnlogradouroChanging(value);
					this.SendPropertyChanging();
					this._logradouro = value;
					this.SendPropertyChanged("logradouro");
					this.OnlogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(5)")]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="VarChar(40)")]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(30)")]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(30)")]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(2)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ddd", DbType="VarChar(4)")]
		public string ddd
		{
			get
			{
				return this._ddd;
			}
			set
			{
				if ((this._ddd != value))
				{
					this.OndddChanging(value);
					this.SendPropertyChanging();
					this._ddd = value;
					this.SendPropertyChanged("ddd");
					this.OndddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(10)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(10)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_cadastro", DbType="Date NOT NULL")]
		public System.DateTime data_cadastro
		{
			get
			{
				return this._data_cadastro;
			}
			set
			{
				if ((this._data_cadastro != value))
				{
					this.Ondata_cadastroChanging(value);
					this.SendPropertyChanging();
					this._data_cadastro = value;
					this.SendPropertyChanged("data_cadastro");
					this.Ondata_cadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_unidade_medida")]
	public partial class unidade_medida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private byte _ativo;
		
		private EntitySet<produto> _produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public unidade_medida()
		{
			this._produto = new EntitySet<produto>(new Action<produto>(this.attach_produto), new Action<produto>(this.detach_produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_unidade_medida", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_unidade_medida", Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidade_medida_produto", Storage="_produto", ThisKey="codigo", OtherKey="unidade_medida")]
		public EntitySet<produto> produto
		{
			get
			{
				return this._produto;
			}
			set
			{
				this._produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produto(produto entity)
		{
			this.SendPropertyChanging();
			entity.unidade_medida1 = this;
		}
		
		private void detach_produto(produto entity)
		{
			this.SendPropertyChanging();
			entity.unidade_medida1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_curso")]
	public partial class curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private string _descricao;
		
		private decimal _investimento;
		
		private string _carga_horaria;
		
		private int _grupo_curso;
		
		private byte _ativo;
		
		private EntityRef<grupo_curso> _grupo_curso1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OninvestimentoChanging(decimal value);
    partial void OninvestimentoChanged();
    partial void Oncarga_horariaChanging(string value);
    partial void Oncarga_horariaChanged();
    partial void Ongrupo_cursoChanging(int value);
    partial void Ongrupo_cursoChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public curso()
		{
			this._grupo_curso1 = default(EntityRef<grupo_curso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_curso", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_curso", Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="descricao_curso", Storage="_descricao", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_investimento", DbType="Decimal(8,2) NOT NULL")]
		public decimal investimento
		{
			get
			{
				return this._investimento;
			}
			set
			{
				if ((this._investimento != value))
				{
					this.OninvestimentoChanging(value);
					this.SendPropertyChanging();
					this._investimento = value;
					this.SendPropertyChanged("investimento");
					this.OninvestimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carga_horaria", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string carga_horaria
		{
			get
			{
				return this._carga_horaria;
			}
			set
			{
				if ((this._carga_horaria != value))
				{
					this.Oncarga_horariaChanging(value);
					this.SendPropertyChanging();
					this._carga_horaria = value;
					this.SendPropertyChanged("carga_horaria");
					this.Oncarga_horariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_grupo_curso", Storage="_grupo_curso", DbType="Int NOT NULL")]
		public int grupo_curso
		{
			get
			{
				return this._grupo_curso;
			}
			set
			{
				if ((this._grupo_curso != value))
				{
					this.Ongrupo_cursoChanging(value);
					this.SendPropertyChanging();
					this._grupo_curso = value;
					this.SendPropertyChanged("grupo_curso");
					this.Ongrupo_cursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_curso_curso", Storage="_grupo_curso1", ThisKey="grupo_curso", OtherKey="codigo", IsForeignKey=true)]
		public grupo_curso grupo_curso1
		{
			get
			{
				return this._grupo_curso1.Entity;
			}
			set
			{
				grupo_curso previousValue = this._grupo_curso1.Entity;
				if (((previousValue != value) 
							|| (this._grupo_curso1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grupo_curso1.Entity = null;
						previousValue.curso.Remove(this);
					}
					this._grupo_curso1.Entity = value;
					if ((value != null))
					{
						value.curso.Add(this);
						this._grupo_curso = value.codigo;
					}
					else
					{
						this._grupo_curso = default(int);
					}
					this.SendPropertyChanged("grupo_curso1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_empresa")]
	public partial class empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private string _cnpj_cpf;
		
		private string _ie_rg;
		
		private string _cep;
		
		private string _logradouro;
		
		private string _numero;
		
		private string _complemento;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _estado;
		
		private string _ddd;
		
		private string _telefone;
		
		private string _celular;
		
		private string _email;
		
		private string _pagina_web;
		
		private System.DateTime _data_cadastro;
		
		private byte _ativo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void Oncnpj_cpfChanging(string value);
    partial void Oncnpj_cpfChanged();
    partial void Onie_rgChanging(string value);
    partial void Onie_rgChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnlogradouroChanging(string value);
    partial void OnlogradouroChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OndddChanging(string value);
    partial void OndddChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onpagina_webChanging(string value);
    partial void Onpagina_webChanged();
    partial void Ondata_cadastroChanging(System.DateTime value);
    partial void Ondata_cadastroChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public empresa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_empresa", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_empresa", Storage="_nome", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnpj_cpf", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string cnpj_cpf
		{
			get
			{
				return this._cnpj_cpf;
			}
			set
			{
				if ((this._cnpj_cpf != value))
				{
					this.Oncnpj_cpfChanging(value);
					this.SendPropertyChanging();
					this._cnpj_cpf = value;
					this.SendPropertyChanged("cnpj_cpf");
					this.Oncnpj_cpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ie_rg", DbType="VarChar(15)")]
		public string ie_rg
		{
			get
			{
				return this._ie_rg;
			}
			set
			{
				if ((this._ie_rg != value))
				{
					this.Onie_rgChanging(value);
					this.SendPropertyChanging();
					this._ie_rg = value;
					this.SendPropertyChanged("ie_rg");
					this.Onie_rgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(15)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logradouro", DbType="VarChar(80)")]
		public string logradouro
		{
			get
			{
				return this._logradouro;
			}
			set
			{
				if ((this._logradouro != value))
				{
					this.OnlogradouroChanging(value);
					this.SendPropertyChanging();
					this._logradouro = value;
					this.SendPropertyChanged("logradouro");
					this.OnlogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(5)")]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="VarChar(40)")]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(30)")]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(30)")]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(2)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ddd", DbType="VarChar(4)")]
		public string ddd
		{
			get
			{
				return this._ddd;
			}
			set
			{
				if ((this._ddd != value))
				{
					this.OndddChanging(value);
					this.SendPropertyChanging();
					this._ddd = value;
					this.SendPropertyChanged("ddd");
					this.OndddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(10)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(10)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagina_web", DbType="VarChar(80)")]
		public string pagina_web
		{
			get
			{
				return this._pagina_web;
			}
			set
			{
				if ((this._pagina_web != value))
				{
					this.Onpagina_webChanging(value);
					this.SendPropertyChanging();
					this._pagina_web = value;
					this.SendPropertyChanged("pagina_web");
					this.Onpagina_webChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_cadastro", DbType="Date NOT NULL")]
		public System.DateTime data_cadastro
		{
			get
			{
				return this._data_cadastro;
			}
			set
			{
				if ((this._data_cadastro != value))
				{
					this.Ondata_cadastroChanging(value);
					this.SendPropertyChanging();
					this._data_cadastro = value;
					this.SendPropertyChanged("data_cadastro");
					this.Ondata_cadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_grupo_curso")]
	public partial class grupo_curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private byte _ativo;
		
		private EntitySet<curso> _curso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public grupo_curso()
		{
			this._curso = new EntitySet<curso>(new Action<curso>(this.attach_curso), new Action<curso>(this.detach_curso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_grupo_curso", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_grupo_curso", Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_curso_curso", Storage="_curso", ThisKey="codigo", OtherKey="grupo_curso")]
		public EntitySet<curso> curso
		{
			get
			{
				return this._curso;
			}
			set
			{
				this._curso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_curso(curso entity)
		{
			this.SendPropertyChanging();
			entity.grupo_curso1 = this;
		}
		
		private void detach_curso(curso entity)
		{
			this.SendPropertyChanging();
			entity.grupo_curso1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_grupo_procedimento")]
	public partial class grupo_procedimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private byte _ativo;
		
		private EntitySet<procedimento> _procedimento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public grupo_procedimento()
		{
			this._procedimento = new EntitySet<procedimento>(new Action<procedimento>(this.attach_procedimento), new Action<procedimento>(this.detach_procedimento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_grupo_procedimento", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_grupo_procedimento", Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_procedimento_procedimento", Storage="_procedimento", ThisKey="codigo", OtherKey="grupo_procedimento")]
		public EntitySet<procedimento> procedimento
		{
			get
			{
				return this._procedimento;
			}
			set
			{
				this._procedimento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_procedimento(procedimento entity)
		{
			this.SendPropertyChanging();
			entity.grupo_procedimento1 = this;
		}
		
		private void detach_procedimento(procedimento entity)
		{
			this.SendPropertyChanging();
			entity.grupo_procedimento1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_grupo_produto")]
	public partial class grupo_produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private byte _ativo;
		
		private EntitySet<produto> _produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public grupo_produto()
		{
			this._produto = new EntitySet<produto>(new Action<produto>(this.attach_produto), new Action<produto>(this.detach_produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_grupo_produto", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_grupo_produto", Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_produto_produto", Storage="_produto", ThisKey="codigo", OtherKey="grupo_produto")]
		public EntitySet<produto> produto
		{
			get
			{
				return this._produto;
			}
			set
			{
				this._produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produto(produto entity)
		{
			this.SendPropertyChanging();
			entity.grupo_produto1 = this;
		}
		
		private void detach_produto(produto entity)
		{
			this.SendPropertyChanging();
			entity.grupo_produto1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_procedimento")]
	public partial class procedimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private string _descricao;
		
		private decimal _valor;
		
		private int _grupo_procedimento;
		
		private byte _ativo;
		
		private EntityRef<grupo_procedimento> _grupo_procedimento1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void OnvalorChanging(decimal value);
    partial void OnvalorChanged();
    partial void Ongrupo_procedimentoChanging(int value);
    partial void Ongrupo_procedimentoChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public procedimento()
		{
			this._grupo_procedimento1 = default(EntityRef<grupo_procedimento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_procedimento", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_procedimento", Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(8,2) NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_grupo_procedimento", Storage="_grupo_procedimento", DbType="Int NOT NULL")]
		public int grupo_procedimento
		{
			get
			{
				return this._grupo_procedimento;
			}
			set
			{
				if ((this._grupo_procedimento != value))
				{
					this.Ongrupo_procedimentoChanging(value);
					this.SendPropertyChanging();
					this._grupo_procedimento = value;
					this.SendPropertyChanged("grupo_procedimento");
					this.Ongrupo_procedimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_procedimento_procedimento", Storage="_grupo_procedimento1", ThisKey="grupo_procedimento", OtherKey="codigo", IsForeignKey=true)]
		public grupo_procedimento grupo_procedimento1
		{
			get
			{
				return this._grupo_procedimento1.Entity;
			}
			set
			{
				grupo_procedimento previousValue = this._grupo_procedimento1.Entity;
				if (((previousValue != value) 
							|| (this._grupo_procedimento1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grupo_procedimento1.Entity = null;
						previousValue.procedimento.Remove(this);
					}
					this._grupo_procedimento1.Entity = value;
					if ((value != null))
					{
						value.procedimento.Add(this);
						this._grupo_procedimento = value.codigo;
					}
					else
					{
						this._grupo_procedimento = default(int);
					}
					this.SendPropertyChanged("grupo_procedimento1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _nome;
		
		private string _descricao;
		
		private int _unidade_medida;
		
		private int _grupo_produto;
		
		private int _fornecedor;
		
		private decimal _valor_compra;
		
		private decimal _margem_lucro;
		
		private decimal _valor_venda;
		
		private System.DateTime _data_cadastro;
		
		private byte _ativo;
		
		private EntityRef<grupo_produto> _grupo_produto1;
		
		private EntityRef<unidade_medida> _unidade_medida1;
		
		private EntityRef<fornecedor> _fornecedor1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    partial void Onunidade_medidaChanging(int value);
    partial void Onunidade_medidaChanged();
    partial void Ongrupo_produtoChanging(int value);
    partial void Ongrupo_produtoChanged();
    partial void OnfornecedorChanging(int value);
    partial void OnfornecedorChanged();
    partial void Onvalor_compraChanging(decimal value);
    partial void Onvalor_compraChanged();
    partial void Onmargem_lucroChanging(decimal value);
    partial void Onmargem_lucroChanged();
    partial void Onvalor_vendaChanging(decimal value);
    partial void Onvalor_vendaChanged();
    partial void Ondata_cadastroChanging(System.DateTime value);
    partial void Ondata_cadastroChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public produto()
		{
			this._grupo_produto1 = default(EntityRef<grupo_produto>);
			this._unidade_medida1 = default(EntityRef<unidade_medida>);
			this._fornecedor1 = default(EntityRef<fornecedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome_produto", Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_unidade_medida", Storage="_unidade_medida", DbType="Int NOT NULL")]
		public int unidade_medida
		{
			get
			{
				return this._unidade_medida;
			}
			set
			{
				if ((this._unidade_medida != value))
				{
					this.Onunidade_medidaChanging(value);
					this.SendPropertyChanging();
					this._unidade_medida = value;
					this.SendPropertyChanged("unidade_medida");
					this.Onunidade_medidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_grupo_produto", Storage="_grupo_produto", DbType="Int NOT NULL")]
		public int grupo_produto
		{
			get
			{
				return this._grupo_produto;
			}
			set
			{
				if ((this._grupo_produto != value))
				{
					this.Ongrupo_produtoChanging(value);
					this.SendPropertyChanging();
					this._grupo_produto = value;
					this.SendPropertyChanged("grupo_produto");
					this.Ongrupo_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_fornecedor", Storage="_fornecedor", DbType="Int NOT NULL")]
		public int fornecedor
		{
			get
			{
				return this._fornecedor;
			}
			set
			{
				if ((this._fornecedor != value))
				{
					this.OnfornecedorChanging(value);
					this.SendPropertyChanging();
					this._fornecedor = value;
					this.SendPropertyChanged("fornecedor");
					this.OnfornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_compra", DbType="Decimal(8,2) NOT NULL")]
		public decimal valor_compra
		{
			get
			{
				return this._valor_compra;
			}
			set
			{
				if ((this._valor_compra != value))
				{
					this.Onvalor_compraChanging(value);
					this.SendPropertyChanging();
					this._valor_compra = value;
					this.SendPropertyChanged("valor_compra");
					this.Onvalor_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_margem_lucro", DbType="Decimal(5,2) NOT NULL")]
		public decimal margem_lucro
		{
			get
			{
				return this._margem_lucro;
			}
			set
			{
				if ((this._margem_lucro != value))
				{
					this.Onmargem_lucroChanging(value);
					this.SendPropertyChanging();
					this._margem_lucro = value;
					this.SendPropertyChanged("margem_lucro");
					this.Onmargem_lucroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_venda", DbType="Decimal(10,2) NOT NULL")]
		public decimal valor_venda
		{
			get
			{
				return this._valor_venda;
			}
			set
			{
				if ((this._valor_venda != value))
				{
					this.Onvalor_vendaChanging(value);
					this.SendPropertyChanging();
					this._valor_venda = value;
					this.SendPropertyChanged("valor_venda");
					this.Onvalor_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_cadastro", DbType="Date NOT NULL")]
		public System.DateTime data_cadastro
		{
			get
			{
				return this._data_cadastro;
			}
			set
			{
				if ((this._data_cadastro != value))
				{
					this.Ondata_cadastroChanging(value);
					this.SendPropertyChanging();
					this._data_cadastro = value;
					this.SendPropertyChanged("data_cadastro");
					this.Ondata_cadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="grupo_produto_produto", Storage="_grupo_produto1", ThisKey="grupo_produto", OtherKey="codigo", IsForeignKey=true)]
		public grupo_produto grupo_produto1
		{
			get
			{
				return this._grupo_produto1.Entity;
			}
			set
			{
				grupo_produto previousValue = this._grupo_produto1.Entity;
				if (((previousValue != value) 
							|| (this._grupo_produto1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._grupo_produto1.Entity = null;
						previousValue.produto.Remove(this);
					}
					this._grupo_produto1.Entity = value;
					if ((value != null))
					{
						value.produto.Add(this);
						this._grupo_produto = value.codigo;
					}
					else
					{
						this._grupo_produto = default(int);
					}
					this.SendPropertyChanged("grupo_produto1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidade_medida_produto", Storage="_unidade_medida1", ThisKey="unidade_medida", OtherKey="codigo", IsForeignKey=true)]
		public unidade_medida unidade_medida1
		{
			get
			{
				return this._unidade_medida1.Entity;
			}
			set
			{
				unidade_medida previousValue = this._unidade_medida1.Entity;
				if (((previousValue != value) 
							|| (this._unidade_medida1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._unidade_medida1.Entity = null;
						previousValue.produto.Remove(this);
					}
					this._unidade_medida1.Entity = value;
					if ((value != null))
					{
						value.produto.Add(this);
						this._unidade_medida = value.codigo;
					}
					else
					{
						this._unidade_medida = default(int);
					}
					this.SendPropertyChanged("unidade_medida1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_fornecedor_produto", Storage="_fornecedor1", ThisKey="fornecedor", OtherKey="codigo", IsForeignKey=true)]
		public fornecedor fornecedor1
		{
			get
			{
				return this._fornecedor1.Entity;
			}
			set
			{
				fornecedor previousValue = this._fornecedor1.Entity;
				if (((previousValue != value) 
							|| (this._fornecedor1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fornecedor1.Entity = null;
						previousValue.produto.Remove(this);
					}
					this._fornecedor1.Entity = value;
					if ((value != null))
					{
						value.produto.Add(this);
						this._fornecedor = value.codigo;
					}
					else
					{
						this._fornecedor = default(int);
					}
					this.SendPropertyChanged("fornecedor1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_fornecedor")]
	public partial class fornecedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo;
		
		private string _razao_social;
		
		private string _nome_fantasia;
		
		private string _tipo_fornecedor;
		
		private string _cnpj_cpf;
		
		private string _ie_rg;
		
		private string _cep;
		
		private string _logradouro;
		
		private string _numero;
		
		private string _complemento;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _estado;
		
		private string _ddd;
		
		private string _telefone;
		
		private string _celular;
		
		private string _email;
		
		private string _pagina_web;
		
		private string _nome_vendedor;
		
		private string _ddd_vendedor;
		
		private string _telefone_vendedor;
		
		private string _celular_vendedor;
		
		private string _email_vendedor;
		
		private System.DateTime _data_cadastro;
		
		private byte _ativo;
		
		private EntitySet<produto> _produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void Onrazao_socialChanging(string value);
    partial void Onrazao_socialChanged();
    partial void Onnome_fantasiaChanging(string value);
    partial void Onnome_fantasiaChanged();
    partial void Ontipo_fornecedorChanging(string value);
    partial void Ontipo_fornecedorChanged();
    partial void Oncnpj_cpfChanging(string value);
    partial void Oncnpj_cpfChanged();
    partial void Onie_rgChanging(string value);
    partial void Onie_rgChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OnlogradouroChanging(string value);
    partial void OnlogradouroChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OndddChanging(string value);
    partial void OndddChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onpagina_webChanging(string value);
    partial void Onpagina_webChanged();
    partial void Onnome_vendedorChanging(string value);
    partial void Onnome_vendedorChanged();
    partial void Onddd_vendedorChanging(string value);
    partial void Onddd_vendedorChanged();
    partial void Ontelefone_vendedorChanging(string value);
    partial void Ontelefone_vendedorChanged();
    partial void Oncelular_vendedorChanging(string value);
    partial void Oncelular_vendedorChanged();
    partial void Onemail_vendedorChanging(string value);
    partial void Onemail_vendedorChanged();
    partial void Ondata_cadastroChanging(System.DateTime value);
    partial void Ondata_cadastroChanged();
    partial void OnativoChanging(byte value);
    partial void OnativoChanged();
    #endregion
		
		public fornecedor()
		{
			this._produto = new EntitySet<produto>(new Action<produto>(this.attach_produto), new Action<produto>(this.detach_produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_fornecedor", Storage="_codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razao_social", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string razao_social
		{
			get
			{
				return this._razao_social;
			}
			set
			{
				if ((this._razao_social != value))
				{
					this.Onrazao_socialChanging(value);
					this.SendPropertyChanging();
					this._razao_social = value;
					this.SendPropertyChanged("razao_social");
					this.Onrazao_socialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_fantasia", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nome_fantasia
		{
			get
			{
				return this._nome_fantasia;
			}
			set
			{
				if ((this._nome_fantasia != value))
				{
					this.Onnome_fantasiaChanging(value);
					this.SendPropertyChanging();
					this._nome_fantasia = value;
					this.SendPropertyChanged("nome_fantasia");
					this.Onnome_fantasiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_fornecedor", DbType="VarChar(2)")]
		public string tipo_fornecedor
		{
			get
			{
				return this._tipo_fornecedor;
			}
			set
			{
				if ((this._tipo_fornecedor != value))
				{
					this.Ontipo_fornecedorChanging(value);
					this.SendPropertyChanging();
					this._tipo_fornecedor = value;
					this.SendPropertyChanged("tipo_fornecedor");
					this.Ontipo_fornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnpj_cpf", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string cnpj_cpf
		{
			get
			{
				return this._cnpj_cpf;
			}
			set
			{
				if ((this._cnpj_cpf != value))
				{
					this.Oncnpj_cpfChanging(value);
					this.SendPropertyChanging();
					this._cnpj_cpf = value;
					this.SendPropertyChanged("cnpj_cpf");
					this.Oncnpj_cpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ie_rg", DbType="VarChar(15)")]
		public string ie_rg
		{
			get
			{
				return this._ie_rg;
			}
			set
			{
				if ((this._ie_rg != value))
				{
					this.Onie_rgChanging(value);
					this.SendPropertyChanging();
					this._ie_rg = value;
					this.SendPropertyChanged("ie_rg");
					this.Onie_rgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(15)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logradouro", DbType="VarChar(80)")]
		public string logradouro
		{
			get
			{
				return this._logradouro;
			}
			set
			{
				if ((this._logradouro != value))
				{
					this.OnlogradouroChanging(value);
					this.SendPropertyChanging();
					this._logradouro = value;
					this.SendPropertyChanged("logradouro");
					this.OnlogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(5)")]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="VarChar(40)")]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="VarChar(30)")]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="VarChar(30)")]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Char(2)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ddd", DbType="VarChar(4)")]
		public string ddd
		{
			get
			{
				return this._ddd;
			}
			set
			{
				if ((this._ddd != value))
				{
					this.OndddChanging(value);
					this.SendPropertyChanging();
					this._ddd = value;
					this.SendPropertyChanged("ddd");
					this.OndddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(10)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(10)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(80)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagina_web", DbType="VarChar(80)")]
		public string pagina_web
		{
			get
			{
				return this._pagina_web;
			}
			set
			{
				if ((this._pagina_web != value))
				{
					this.Onpagina_webChanging(value);
					this.SendPropertyChanging();
					this._pagina_web = value;
					this.SendPropertyChanged("pagina_web");
					this.Onpagina_webChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_vendedor", DbType="VarChar(80)")]
		public string nome_vendedor
		{
			get
			{
				return this._nome_vendedor;
			}
			set
			{
				if ((this._nome_vendedor != value))
				{
					this.Onnome_vendedorChanging(value);
					this.SendPropertyChanging();
					this._nome_vendedor = value;
					this.SendPropertyChanged("nome_vendedor");
					this.Onnome_vendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ddd_vendedor", DbType="VarChar(4)")]
		public string ddd_vendedor
		{
			get
			{
				return this._ddd_vendedor;
			}
			set
			{
				if ((this._ddd_vendedor != value))
				{
					this.Onddd_vendedorChanging(value);
					this.SendPropertyChanging();
					this._ddd_vendedor = value;
					this.SendPropertyChanged("ddd_vendedor");
					this.Onddd_vendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone_vendedor", DbType="VarChar(10)")]
		public string telefone_vendedor
		{
			get
			{
				return this._telefone_vendedor;
			}
			set
			{
				if ((this._telefone_vendedor != value))
				{
					this.Ontelefone_vendedorChanging(value);
					this.SendPropertyChanging();
					this._telefone_vendedor = value;
					this.SendPropertyChanged("telefone_vendedor");
					this.Ontelefone_vendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular_vendedor", DbType="VarChar(10)")]
		public string celular_vendedor
		{
			get
			{
				return this._celular_vendedor;
			}
			set
			{
				if ((this._celular_vendedor != value))
				{
					this.Oncelular_vendedorChanging(value);
					this.SendPropertyChanging();
					this._celular_vendedor = value;
					this.SendPropertyChanged("celular_vendedor");
					this.Oncelular_vendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_vendedor", DbType="VarChar(80)")]
		public string email_vendedor
		{
			get
			{
				return this._email_vendedor;
			}
			set
			{
				if ((this._email_vendedor != value))
				{
					this.Onemail_vendedorChanging(value);
					this.SendPropertyChanging();
					this._email_vendedor = value;
					this.SendPropertyChanged("email_vendedor");
					this.Onemail_vendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_cadastro", DbType="Date NOT NULL")]
		public System.DateTime data_cadastro
		{
			get
			{
				return this._data_cadastro;
			}
			set
			{
				if ((this._data_cadastro != value))
				{
					this.Ondata_cadastroChanging(value);
					this.SendPropertyChanging();
					this._data_cadastro = value;
					this.SendPropertyChanged("data_cadastro");
					this.Ondata_cadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ativo", DbType="TinyInt NOT NULL")]
		public byte ativo
		{
			get
			{
				return this._ativo;
			}
			set
			{
				if ((this._ativo != value))
				{
					this.OnativoChanging(value);
					this.SendPropertyChanging();
					this._ativo = value;
					this.SendPropertyChanged("ativo");
					this.OnativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_fornecedor_produto", Storage="_produto", ThisKey="codigo", OtherKey="fornecedor")]
		public EntitySet<produto> produto
		{
			get
			{
				return this._produto;
			}
			set
			{
				this._produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produto(produto entity)
		{
			this.SendPropertyChanging();
			entity.fornecedor1 = this;
		}
		
		private void detach_produto(produto entity)
		{
			this.SendPropertyChanging();
			entity.fornecedor1 = null;
		}
	}
}
#pragma warning restore 1591
